protected/controllers/ClientController.php
<?php
class ClientController extends Controller
{
    public function filters()
    {
        return array(
            'accessControl',
            'postOnly + delete',
        );
    }
    public function accessRules()
    {
        return array(
            array('allow',
                'actions' => array('GetCount', /*'Index',*/
                    'ShoppingCart', 'Cabinet',
                    'Cartclear', 'Buycart', 'StillAlive', 'Balanse', 'History',
                    'GetNextCount', 'ShoppingCart2'
                ),
                'roles' => array('User'),
            ),
            array('deny',
                'users' => array('*'),
            ),
        );
    }
    public function actionGetNextCount()
    {
        if (Check::Value($_POST))
        {
            if (Check::Value($_POST['text']))
            {
                if (Check::Value($_POST['field']))
                {
                    if (Check::Value($_POST['kill']))
                    {
                        $text = Check::Clear($_POST['text']);
                        $field = Check::Clear($_POST['field']);
                        $kill = Check::Clear($_POST['kill']);
                        $prev = array();
                        if(Check::Value($_POST['prev']))
                        {
                                $prev = $_POST['prev'];
                                $prev = unserialize($prev);
                        }
                        $arr = array('country', 'state', 'city', 'zip');
                        if (in_array($field, $arr))
                        {
                            $i = array_search($field, $arr);
                            $i++;
                            if (array_key_exists($i, $arr))
                            {
                                $prev[$field] = $text;
                                $next = $arr[$i];
                                $result = Ipall::GetNextCount($next, $prev);
                                $prev = serialize($prev);
                                $this->renderPartial('GetTr', array('prev'=>$prev, 'result' => $result, 'next' => $next, 'kill' => $kill));
                            }
                        }
                    }
                }
            }
        }
    }
    public function actionBalanse()
    {
        $this->layout = '//layouts/column3';
        if (!Yii::app()->user->isGuest)
        {
            $id = Yii::app()->user->getId();
            if (Check::Value($id))
            {
                $cnt = Ipall::GetUsserCartCount($id);
                $this->render('Balanse', array('cnt' => $cnt));
            }
        }
    }
    public function History()
    {
        $this->layout = '//layouts/column3';
        if (!Yii::app()->user->isGuest)
        {
            $id = Yii::app()->user->getId();
            if (Check::Value($id))
            {
                $cnt = Ipall::GetUsserCartCount($id);
                $cntbuy = Ipall::GetUsserBuyedIP($id);
                $db = new Ipall();
                $result = $db->GetUsserHistory($id);
                $dates = Ipall::GetUsserDateHistoryIP($id);
                $arr = array('result' => $result,
                    'cnt' => $cnt,
                    'cntbuy' => $cntbuy,
                    'dates' => $dates,
                );
                return $arr;
            }
        }
    }
    public function actionHistory()
    {
        $this->layout = '//layouts/column3';
        if (!Yii::app()->user->isGuest)
        {
            $id = Yii::app()->user->getId();
            if (Check::Value($id))
            {
                $cnt = Ipall::GetUsserCartCount($id);
                $cntbuy = Ipall::GetUsserBuyedIP($id);
                $db = new Ipall();
                $result = $db->GetUsserHistory($id);
                $dates = Ipall::GetUsserDateHistoryIP($id);
                $this->render('History',
                    array('result' => $result,
                        'cnt' => $cnt,
                        'cntbuy' => $cntbuy,
                        'dates' => $dates,
                    ));
            }
        }
    }
    public function actionCabinet()
    {
        $this->layout = '//layouts/column3';
        if (!Yii::app()->user->isGuest)
        {
            $id = Yii::app()->user->getId();
            if (Check::Value($id))
            {
                $db = new Ipall();
                $result = $db->GetUsserCart($id);
                $db = new Management();
                $price = $db->getPrice();
                //$this->render('Cabinet', array('result' => $result, 'price' => $price));
                $History = $this->History();
                $this->render('Cabinet', array('result' => $result, 'price' => $price, 'History' => $History));
            }
        }
    }
    public function actionCartclear()
    {
        if (!Yii::app()->user->isGuest)
        {
            $id = Yii::app()->user->getId();
            if (Check::Value($id))
            {
                $db = new Ipall();
                $db->Cartclear($id);
            }
        }
    }
    public function actionBuycart()
    {
        if (!Yii::app()->user->isGuest)
        {
            $id = Yii::app()->user->getId();
            if (Check::Value($id))
            {
                $db = new Management();
                $price = $db->getPrice();
                $cnt = Ipall::GetUsserCartCount($id);
                $cost = $price * $cnt;
                $balance = Users::GetBalans();
                if ($balance < $cost)
                {
                    $this->renderPartial('AlertMessage', array('alertmessage' => 'lovbalance'));
                }
                else
                {
                    $newbal = $balance - $cost;
                    Ipall::UserPayForIp($id);
                    Users::SetBalans($newbal);
                    $this->renderPartial('AlertMessage', array('alertmessage' => 'suchespayet'));
                }
            }
        }
    }
    /*public function actionIndex()
    {
        $this->render('index');
    }*/
    public function actionShoppingCart2()
    {
        $alertmessage = 'default';
        try
        {
            if (Check::Value($_POST))
            {
                if (Check::Value($_POST['field']))
                {
                    if (Check::Value($_POST['seartext']))
                    {
                        if (Check::Value($_POST['count']))
                        {
                            $field = $_POST['field'];
                            $seartext = $_POST['seartext'];
                            $count = $_POST['count'];

                            $prev = array();
                            if(Check::Value($_POST['prev']))
                            {
                                $prev = $_POST['prev'];
                                $prev = unserialize($prev);
                            }

                            $sel = $field;
                            $sel = mb_strtolower($sel, 'UTF-8');
                            $val = $seartext;
                            $arr = array('country', 'state', 'city', 'zip');
                            if (in_array($sel, $arr))
                            {
                                $res = $this->GoNext($sel, $val);
                                if (Check::Value($res))
                                {
                                    if ($res['count'] < $count)
                                    {
                                        $alertmessage = 'toolow';
                                    }
                                    else
                                    {
                                        if (!Yii::app()->user->isGuest)
                                        {
                                            $id = Yii::app()->user->getId();
                                            $sel = $field;
                                            $sel = mb_strtolower($sel, 'UTF-8');
                                            $val = $seartext;
                                            $db = new Ipall();
                                            $db->ByiIp2($id, $count, $sel, $val, $prev);
                                            $alertmessage = 'success';
                                        }
                                    }
                                }
                                else
                                {
                                    $alertmessage = 'toolow';
                                }
                            }
                        }
                    }
                }
            }
        }
        catch (Exception $e)
        {
            $alertmessage = 'error';
        }
        $this->renderPartial('AlertMessage', array('alertmessage' => $alertmessage, 'count' => $count));
    }
    public function actionShoppingCart()
    {
        $alertmessage = 'default';
        try
        {
            if (Check::Value($_POST))
            {
                if (Check::Value($_POST['field']))
                {
                    if (Check::Value($_POST['seartext']))
                    {
                        if (Check::Value($_POST['count']))
                        {
                            $field = $_POST['field'];
                            $seartext = $_POST['seartext'];
                            $count = $_POST['count'];
                            $sel = $field;
                            $sel = mb_strtolower($sel, 'UTF-8');
                            $val = $seartext;
                            $arr = array('country', 'state', 'city', 'zip');
                            if (in_array($sel, $arr))
                            {
                                $res = $this->GoNext($sel, $val);
                                if (Check::Value($res))
                                {
                                    if ($res['count'] < $count)

protected/controllers/IpallController.php
<?php
class IpallController extends Controller
{
    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column2';
    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + delete', // we only allow deletion via POST request
        );
    }
    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array('allow',
                'actions' => array('View', 'Create', 'Update', 'Delete', 'Index', 'Admin'),
                'roles' => array('Admin'),
            ),
            array('deny',
                'users' => array('*'),
            ),
        );
    }
    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id)
    {
        $this->render('view', array(
            'model' => $this->loadModel($id),
        ));
    }
    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate()
    {
        $model = new Ipall;
        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);
        if (isset($_POST['Ipall']))
        {
            $model->attributes = $_POST['Ipall'];
            if ($model->save())
                $this->redirect(array('view', 'id' => $model->id));
        }
        $this->render('create', array(
            'model' => $model,
        ));
    }
    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id)
    {
        $model = $this->loadModel($id);
        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);
        if (isset($_POST['Ipall']))
        {
            $model->attributes = $_POST['Ipall'];
            if ($model->save())
                $this->redirect(array('view', 'id' => $model->id));
        }
        $this->render('update', array(
            'model' => $model,
        ));
    }
    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id)
    {
        $this->loadModel($id)->delete();
        // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
        if (!isset($_GET['ajax']))
            $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
    }
    /**
     * Lists all models.
     */
    public function actionIndex()
    {
        $dataProvider = new CActiveDataProvider('Ipall');
        $this->render('index', array(
            'dataProvider' => $dataProvider,
        ));
    }
    /**
     * Manages all models.
     */
    public function actionAdmin()
    {
        $model = new Ipall('search');
        $model->unsetAttributes();  // clear any default values
        if (isset($_GET['Ipall']))
            $model->attributes = $_GET['Ipall'];
        $this->render('admin', array(
            'model' => $model,
        ));
    }
    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer $id the ID of the model to be loaded
     * @return Ipall the loaded model
     * @throws CHttpException
     */
    public function loadModel($id)
    {
        $model = Ipall::model()->findByPk($id);
        if ($model === null)
            throw new CHttpException(404, 'The requested page does not exist.');
        return $model;
    }
    /**
     * Performs the AJAX validation.
     * @param Ipall $model the model to be validated
     */
    protected function performAjaxValidation($model)
    {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'ipall-form')
        {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }
}

protected/views/layouts/column1.php
<?php
$this->beginContent('//layouts/main');
?>
    <div id="content">
        <?php
        echo $content;
        ?>
    </div><!-- content -->
<?php
$this->endContent();
?>

protected/views/layouts/column2.php
<?php
$this->beginContent('//layouts/main');
?>
    <div class="span-19">
        <div id="content">
            <?php echo $content; ?>
        </div>
        <!-- content -->
    </div>
    <div class="span-5 last">
        <div id="sidebar">
            <?php
            $this->beginWidget('zii.widgets.CPortlet', array(
                'title' => Yii::t('main-ui', 'Operations'),
            ));
            $this->widget('zii.widgets.CMenu', array(
                'items' => $this->menu,
                'htmlOptions' => array('class' => 'nav nav-pills nav-stacked'),
                'encodeLabel' => false,
            ));
            $this->endWidget();
            ?>
        </div>
        <!-- sidebar -->
    </div>
<?php $this->endContent(); ?>

protected/views/layouts/column3.php
<?php
$this->beginContent('//layouts/main');
?>
    <div class="span-19">
        <div id="content">
            <?php echo $content; ?>
        </div>
        <!-- content -->
    </div>
    <div class="span-5 last">
        <div id="sidebar">
            <?php
            $this->beginWidget('zii.widgets.CPortlet', array(
                'title' => Yii::t('main-ui', ''),
            ));
            $this->widget('zii.widgets.CMenu', array(
                'items' => $this->menu,
                'htmlOptions' => array('class' => 'nav nav-pills nav-stacked'),
                'encodeLabel' => false,
            ));
            $this->endWidget();
            ?>
        </div>
        <!-- sidebar -->
    </div>
<?php $this->endContent(); ?>

protected/views/layouts/main.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="language" content="en"/>
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/screen.css"
          media="screen, projection"/>
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/print.css"
          media="print"/>
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css"/>
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/bootstrap.css"/>
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/MyStyle.css"/>
    <script src="<?php echo Yii::app()->request->baseUrl; ?>/JavaScript/jquery-2.1.1.js"></script>

    <link rel="shortcut icon" type="image/x-icon" href="<?php echo Yii::app()->request->baseUrl; ?>/images/logo.png"/>

    <title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>
<body>
<style>
    .body
    {
        background: url(<?php echo Yii::app()->request->baseUrl; ?>/images/logo.png);
    }
</style>
<div class="container" id="page">
    <?php
    $arr = array();
    $role = Yii::app()->user->getRole();
    if (!Yii::app()->user->isGuest)
    {
        echo '
				<div class="bs-component1">
					<div class="navbar navbar-default active">
						<div class="navbar-collapse collapse navbar-responsive-collapse">';
        $logoimg = Yii::app()->request->baseUrl . '/images/logo.png';
        echo "<ul class='nav navbar-nav navbar-left'>
                <li>
                    <span>
                        <a href='/index.php?r=site/index'>
                            <img class='navbar-left' style='height: 50px' src='$logoimg'>
                        </a>
                    </span>
                </li>
            </ul>";
        //$logoimg = Yii::app()->request->baseUrl.'/images/logo.png';
        //$arr[] = array('label' => "<img class='navbar-left' style='height: 50px' src='$logoimg'></img>");
        $arr[] = array('label' => Yii::t('main-ui', 'Главная'), 'url' => array('/site/index'),);
        if ($role == 'Admin')
        {
            $arr[] = array('label' => Yii::t('main-ui', 'Пользователи'), 'url' => array('/Users/admin'));
            $arr[] = array('label' => Yii::t('main-ui', 'Новости'), 'url' => array('/News/admin'));
            $arr[] = array('label' => Yii::t('main-ui', 'Все IP'), 'url' => array('/ipall/admin'));
            $arr[] = array('label' => Yii::t('main-ui', 'Админ'), 'url' => array('/Admin/index'));
            //$arr[] = array('label' => Yii::t('main-ui', 'Chat'), 'url' => array('/Chat/AdminAllChat'));
            $newmes = Chat::AdminGetNewMesCnt();
            $str = '';
            if (Check::Value($newmes))
            {
                $str = " <span class='badge'>$newmes</span>";
            }
            $arr[] = array('label' => "Чат$str", 'url' => array('/Chat/AdminAllChat'));
        }
        if ($role == 'User')
        {
            //$arr[] = array('label' => Yii::t('main-ui', 'Search IP'), 'url' => array('/client/index'));
            $arr[] = array('label' => Yii::t('main-ui', 'Кабинет'), 'url' => array('/client/Cabinet'));
            $id = Yii::app()->user->getId();
            $newmes = Chat::UserGetNewMesCnt($id);
            $str = '';
            if (Check::Value($newmes))
            {
                $str = " <span class='badge'>$newmes</span>";
            }
            $id = Yii::app()->user->getId();
            $arr[] = array('label' => "Чат$str", 'url' => array('/Chat/Userchat&id=' . $id));
            $balance = Users::GetBalans();
            $arr[] =
                array('label' =>
                    "<strong class='text-danger'  style='font-size: 18px'>$balance</strong> <span style='color: darkgreen; font-size: 16px;'>USD</span>", 'url' => array('/client/Balanse'));
        }
        $arr[] = array('label' => Yii::t('main-ui', 'Выход') . ' (' . Yii::app()->user->name . ')', 'url' => array('/site/logout'), 'visible' => !Yii::app()->user->isGuest);
        $this->widget('zii.widgets.CMenu',
            array(
                'items' => $arr,
                'htmlOptions' => array('class' => 'nav navbar-nav navbar-right'),
                'encodeLabel' => false,
            ));
        echo '	</div>
					</div>
				</div>';
        ?>
        <script>
            setInterval(function ()
            {
                $.ajax({
                    url: '?r=site/StillAlive',
                    data: {},
                    type: 'POST',
                    success: function (msg)
                    {
                        if (msg != 'StillAlive')
                        {
                            $(location).attr("href", "./index.php?r=site/logout")
                        }
                    }
                });
            }, 3000);
        </script>
    <?php
    }
    ?>
    <?= $content; ?>
    <div class="clear"></div>
    <div id="footer"></div>
</div>
</body>
</html>